name: brewery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  hooks_riverpod: ^2.1.1
  intl: any
  json_annotation: ^4.7.0
  roggle: ^0.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner: ^2.3.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.0
  grinder: ^0.9.2
  json_serializable: ^6.5.4
  pedantic_mono: ^1.20.0

flutter:
  uses-material-design: true
