name: brewery
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
  sdk: 3.7.2
  flutter: 3.29.2

dependencies:
  animations: ^2.0.11
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  talker: ^4.7.1
  talker_dio_logger: ^4.7.1
  talker_flutter: ^4.7.1
  talker_riverpod_logger: ^4.7.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
