name: brewery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  hooks_riverpod: ^2.0.0-dev.9
  intl: any
  json_annotation: ^4.7.0
  roggle: ^0.2.1+1

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  pedantic_mono: ^1.18.0

flutter:
  uses-material-design: true
