name: Released Releases

on:
  release:
    types:
      - released

env:
  FLUTTER_VERSION: "3.3.7" # FIXME

jobs:
  release:
    runs-on: macos-latest
    steps:
      ### Setup ###
      - uses: actions/checkout@v3

      - name: CocoaPods Cache
        if: ${{ runner.os == 'macOS' }}
        uses: actions/cache@v4
        with:
          path: ./macos/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}-v1
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install-flutter.sh $FLUTTER_VERSION

      ### Build ###
      - name: Build
        run: flutter build macos --release

      ### Deploy ###
      - name: zip App
        working-directory: ./build/macos/Build/Products/Release
        run: zip -r Brewery.zip Brewery.app

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: ./build/macos/Build/Products/Release/Brewery.zip
